import { DisplaySubject, TagSubject } from "./Tag.utils.js";
import { TagSupport } from "./TagSupport.class.js";
import { Subject } from "./Subject.js";
import { TemplaterResult } from "./templater.utils.js";
import { Tag } from "./Tag.class.js";
import { TagArraySubject } from "./processTagArray.js";
type ExistingSubject = Subject<Tag> | TemplaterResult | TagSubject | TagArraySubject | DisplaySubject;
export declare function updateExistingValue(existing: ExistingSubject, value: TemplaterResult | Tag[] | TagSupport | Function | Subject<any>, ownerTag: Tag): void;
export declare function destroyTagMemory(existingTag: Tag, existingSubject: TagSubject): void;
export {};
