export { getNewGlobal } from './update/getNewGlobal.function.js'
export * from './tag.types.js'
export * from './cycles/index.js'
export { getDomMeta } from './domMetaCollector.js'
export * from './update/index.js'
export * from '../TagJsTags/tag.function.js'
export * from './getDomTag.function.js'
export * from './tag.utils.js'
export * from './html.js'
export * from './ValueTypes.enum.js'
export * from './update/oneRenderToSupport.function.js'
export * from './getTemplaterResult.function.js'
export * from './checkDestroyPrevious.function.js'
export * from './checkTagValueChange.function.js'
export * from './Context.types.js'

export * from './tagElement.js'
export { variablePrefix } from './DomTag.type.js'
export { paint } from '../render/paint.function.js'
export { hasPropChanges } from './hasPropChanges.function.js'
export { PropWatches } from '../TagJsTags/tag.function.js'
export { output } from './output.function.js'
export { guaranteeInsertBefore } from './guaranteeInsertBefore.function.js'
export { tagValueUpdateHandler } from './update/tagValueUpdateHandler.function.js'

export type { DomTag } from './DomTag.type.js'
export type { StringTag } from './StringTag.type.js'
export type { AnySupport } from './AnySupport.type.js'
export type { ProcessInit } from './ProcessInit.type.js'
export type { TemplateValue } from './TemplateValue.type.js'
export type { ContextItem } from './ContextItem.type.js'
export type { SupportContextItem } from './SupportContextItem.type.js'
export type { ContextStateSupport } from './ContextStateMeta.type.js'
