export declare const arrays: import("taggedjs").TaggedFunction<() => ((...children: import("taggedjs").TagChildContent[]) => import("taggedjs").ElementFunction & import("taggedjs").CombinedElementFunctions) & import("taggedjs/js/TagJsTags/TagJsTag.type.js").ReadOnlyVar & {
    tagName: string;
    innerHTML: any[];
    attributes: import("taggedjs/js/interpolations/optimizers/ObjectNode.types.js").Attribute[];
    contentId: number;
    elementFunctions: typeof import("taggedjs/js/elements/elementFunctions.js").elementFunctions;
    contexts?: import("taggedjs/js/TagJsTags/TagJsTag.type.js").TagJsTag<any>[];
    listeners: import("taggedjs/js/elements/ElementVarBase.type.js").MockElmListener[];
    allListeners: import("taggedjs/js/elements/ElementVarBase.type.js").MockElmListener[];
} & {
    key: import("taggedjs").KeyFunction;
    style: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    id: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    class: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    href: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    value: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    placeholder: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    minLength: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    maxLength: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    src: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    type: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    title: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    disabled: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    checked: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    selected: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    cellPadding: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    cellSpacing: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    border: import("taggedjs/js/elements/attributeCallables.js").AttributeCallable;
    attr: (nameOrValue: import("taggedjs/js/elements/ElementFunction.type.js").AttrValue, value?: import("taggedjs/js/elements/ElementFunction.type.js").AttrValue) => import("taggedjs").ElementFunction;
    attrs: (nameValuePairs: {
        [name: string]: import("taggedjs/js/elements/ElementFunction.type.js").AttrValue;
    }) => import("taggedjs").ElementFunction;
    contextMenu: (callback: (e: import("taggedjs").InputElementTargetEvent) => any) => import("taggedjs").ElementFunction;
    onClick: (callback: (e: import("taggedjs").InputElementTargetEvent) => any) => import("taggedjs").ElementFunction;
    onChange: (callback: (e: import("taggedjs").InputElementTargetEvent) => any) => import("taggedjs").ElementFunction;
    onInput: (callback: (e: import("taggedjs").InputElementTargetEvent) => any) => import("taggedjs").ElementFunction;
    onKeyup: (callback: (e: import("taggedjs").InputElementTargetEvent) => any) => import("taggedjs").ElementFunction;
    onKeydown: (callback: (e: import("taggedjs").InputElementTargetEvent) => any) => import("taggedjs").ElementFunction;
    onMouseover: (callback: (e: import("taggedjs").InputElementTargetEvent) => any) => import("taggedjs").ElementFunction;
    onMouseout: (callback: (e: import("taggedjs").InputElementTargetEvent) => any) => import("taggedjs").ElementFunction;
}>;
