export declare function elmCount(selector: string): number;
export declare function query(query: string): HTMLElement[];
export declare function focus(q: string): void;
export declare function click(q: string): void;
export declare function keydownOn(input: Element, key: string): void;
export declare function keyupOn(input: Element, key?: string): void;
export declare function clickOne(q: string, index?: number): void;
export declare function html(q: string): string;
export declare function byId(id: string): HTMLElement;
export declare function htmlById(id: string): string;
export declare function lastById(id: string): Element;
