export { getNewGlobal } from './update/getNewGlobal.function.js';
export * from './tag.types.js';
export { getDomMeta } from './domMetaCollector.js';
export * from './tag.function.js';
export * from './getDomTag.function.js';
export * from './tag.utils.js';
export * from './html.js';
export * from './ValueTypes.enum.js';
export * from './update/oneRenderToSupport.function.js';
export * from './getTemplaterResult.function.js';
export * from './checkDestroyPrevious.function.js';
export * from './checkTagValueChange.function.js';
export * from './Context.types.js';
export * from './tagElement.js';
export { variablePrefix } from './getDomTag.function.js';
export { paint } from '../render/paint.function.js';
export { processFirstSubjectValue } from './update/processFirstSubjectValue.function.js';
export { hasPropChanges } from './hasPropChanges.function.js';
export { PropWatches } from './tag.function.js';
export { output } from './output.function.js';
export { checkSimpleValueChange, deleteSimpleValue } from './checkSimpleValueChange.function.js';
//# sourceMappingURL=index.js.map